### PR TITLE
INFRA-176: Add sonar-project.properties - cfg file for sonarcloud

### PR DESCRIPTION
**Pull request by tomaso**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by helobinvn** [comment]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ruby-decrypt-gate-PR3

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-decrypt-merge-compliance-check/1/ : SUCCESS in 25s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-decrypt-sonarqube-scan-zuul-gate/1/ : SUCCESS in 40s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-decrypt-fossa-scanning-zuul/1/ : SUCCESS in 1m 06s (non-voting)

**Pull request merged**
